security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  role_hierarchy:
    ROLE_ADMIN: [ROLE_USER]
    ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_USER]

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider

      form_login:
        login_path: app_login
        check_path: app_login
        enable_csrf: true # Enables CSRF protection for login forms
        default_target_path: /profile # Redirect after login
        always_use_default_target_path: false
        csrf_token_id: authenticate

      logout:
        path: app_logout
        target: /

      remember_me:
        secret: "%kernel.secret%"
        lifetime: 2592000 # 30 days
        path: /

      switch_user: true

  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/profile, roles: ROLE_USER }
    - {
        path: ^/,
        roles: PUBLIC_ACCESS,
        allow_if: "not is_granted('ROLE_BANNED')",
      }

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4 # Lowest possible value for bcrypt
        time_cost: 3 # Lowest possible value for argon
        memory_cost: 10 # Lowest possible value for argon
